[WIP] service and directive add
ng-web-apis/geolocation pull request #1
Opened 2020-01-23 15:21 UTC by vladimirpotekhin

2020-01-23 15:41 UTC, waterplea commented on projects/demo/src/app/app.component.ts
> +    positions: Position | null = null;
position, without s

2020-01-23 18:24 UTC, MarsiBarsi commented on projects/demo/src/app/app.component.html
> +Demo
демо можно будет еще посвистельнопердельнее сделать

2020-01-23 18:24 UTC, MarsiBarsi commented on projects/geolocation/src/directives/watchPosition.directive.ts
> +    selector: '[WaWatchPosition]',
с маленькой буквы

2020-01-23 18:24 UTC, MarsiBarsi commented on projects/geolocation/src/directives/watchPosition.directive.ts
> +        this.watchPositionId = this.navigatorRef.geolocation.watchPosition(
можно еще сделать некий watcher через `new Observable((observer: Observer<string>) => {...}` и мб даже такую штуку положить в публичное апи. @waterplea @vladimirpotekhin что думаете?

2020-01-28 15:33 UTC, MarsiBarsi commented on projects/geolocation/src/services/geolocation.service.spec.ts
> +describe('Geolocation service', () => {
coverage сотка?

2020-01-29 10:26 UTC, vladimirpotekhin commented on projects/geolocation/src/services/geolocation.service.spec.ts
> +describe('Geolocation service', () => {
теперь да)

2020-01-30 06:32 UTC, MarsiBarsi commented on projects/demo/src/app/app.component.ts
> +        !this.watchSubscription
хипстерим... :)

2020-01-30 06:32 UTC, MarsiBarsi commented on projects/demo/src/app/map/map.component.ts
> +            (this.initialCoords && this.initialCoords.latitude + coordinates.latitude)! *
а зчем тут `!`?

2020-02-01 19:05 UTC, MarsiBarsi commented
@waterplea айда ревьюху...

2020-02-01 21:15 UTC, waterplea requested changes

2020-02-01 21:15 UTC, waterplea commented on projects/geolocation/src/module.ts
> -export class PaymentRequestModule {}
Этот файл ведь не нужен?

2020-02-01 21:15 UTC, waterplea commented on projects/geolocation/src/tokens/geolocation-support.ts
> +                window !== null && !!window.navigator && !!window.navigator.geolocation
На null можно не проверять

2020-02-01 21:15 UTC, waterplea commented on projects/geolocation/src/services/geolocation.service.ts
> +    clearWatch() {
Зачем публичный метод?

2020-02-01 21:15 UTC, waterplea commented on projects/geolocation/src/services/geolocation.service.ts
> +        private readonly positionOptions?: PositionOptions,
Опциональный незапровайженный токен - не undefined а null. Кроме того он не опциональный, у тебя есть фабрика на значение по дефолту, так что он всегда будет.

2020-02-01 21:15 UTC, waterplea commented on projects/geolocation/src/services/geolocation.service.ts
> +        return this.pipe(
Если подписаться, отписаться и снова подписаться - это правильно сработает? Не закомплитится после последней отписки?

2020-02-02 10:40 UTC, vladimirpotekhin commented on projects/demo/src/app/app.component.ts
> +        !this.watchSubscription
переписал)

2020-02-02 10:41 UTC, vladimirpotekhin commented on projects/demo/src/app/map/map.component.ts
> +            (this.initialCoords && this.initialCoords.latitude + coordinates.latitude)! *
done

2020-02-02 10:41 UTC, vladimirpotekhin commented on projects/geolocation/src/module.ts
> -export class PaymentRequestModule {}
да, удалил

2020-02-02 10:41 UTC, vladimirpotekhin commented on projects/geolocation/src/tokens/geolocation-support.ts
> +                window !== null && !!window.navigator && !!window.navigator.geolocation
убрал проверку

2020-02-02 10:41 UTC, vladimirpotekhin commented on projects/geolocation/src/services/geolocation.service.ts
> +    clearWatch() {
удалил метод

2020-02-02 10:42 UTC, vladimirpotekhin commented on projects/geolocation/src/services/geolocation.service.ts
> +        private readonly positionOptions?: PositionOptions,
убрал декоратор

2020-02-02 10:45 UTC, vladimirpotekhin commented on projects/geolocation/src/services/geolocation.service.ts
> +        return this.pipe(
После последней отписки вызовется clearWatch(id) с текущим id, а при следующей подписке создастся новый watchPosition и будет шариться между всеми подписчиками - проверил, отрабатывает корректно

2020-02-02 10:50 UTC, vladimirpotekhin commented
README и демку причесать в отдельном PR уже планирую

2020-02-02 11:13 UTC, MarsiBarsi approved these changes

2020-02-03 12:24 UTC, merged