[WIP] chore(all): add readme and partially improve demo
ng-web-apis/geolocation pull request #2
Opened 2020-02-06 15:06 UTC by vladimirpotekhin

2020-02-06 20:20 UTC, MarsiBarsi commented on README.md
> +constructor(private readonly geolocationService: GeolocationService) {}
хм, а может этот сервис везде как `geolocation$` называть? @waterplea @vladimirpotekhin что думаете?

2020-02-07 12:11 UTC, vladimirpotekhin commented on README.md
> +constructor(private readonly geolocationService: GeolocationService) {}
пожалуй, так правильнее, перепишу с geolocation$

2020-02-07 17:58 UTC, waterplea requested changes
Демо не смотрел, в понедельник стяну и гляну.

2020-02-07 17:58 UTC, waterplea commented on README.md
>  This is a library for declarative use of [Geolocation API](https://developer.mozilla.org/en-US/docs/Web/API/Geolocation_API) with Angular 6+.
Я бы лучше написал: This is an Observer based abstraction over Geolocation API to use with Angular

2020-02-07 17:58 UTC, waterplea commented on README.md
> +When the last subscriber unsubscribes, the service will automatically execute the clearWatch function with the current watchId
Это подробности имплементации, лучше тут написать Service is cold, meaning if there are no Subscribers, it doesn't track position. Или типа того.

2020-02-07 17:58 UTC, waterplea commented on README.md
> +If you need to get position just once and stop observing user location, you can subscribe to geolocationService and use take(1) rxJs operator:
RxJs, r большая

2020-02-07 17:58 UTC, waterplea commented on README.md
> +GeolocationService is an observable, that emits [Position](https://developer.mozilla.org/en-US/docs/Web/API/GeolocationPosition) object
Observable с большой буквы

2020-02-07 17:58 UTC, waterplea commented on README.md
> +@Component({
Токен ведь глобальный? Давай в примере AppModule, а не компонент

2020-02-11 08:06 UTC, waterplea approved these changes

2020-02-11 08:07 UTC, merged